create table year_names(id int, name varchar);

insert into year_names values(1,'ప్రభవ');
insert into year_names values(2,'విభవ');
insert into year_names values(3,'శుక్ల');
insert into year_names values(4,'ప్రమోద్యూత');
insert into year_names values(5,'ప్రజోత్పత్తి');
insert into year_names values(6,'ఆంగీరస');
insert into year_names values(7,'శ్రీముఖ');
insert into year_names values(8,'భావ');
insert into year_names values(9,'యువ');
insert into year_names values(10,'ధాత');
insert into year_names values(11,'ఈశ్వర');
insert into year_names values(12,'బహుధాన్య');
insert into year_names values(13,'ప్రమాధి');
insert into year_names values(14,'విక్రమ');
insert into year_names values(15,'వృష');
insert into year_names values(16,'చిత్రభాను');
insert into year_names values(17,'స్వభాను');
insert into year_names values(18,'తారణ');
insert into year_names values(19,'పార్థివ');
insert into year_names values(20,'వ్యయ');
insert into year_names values(21,'సర్వజిత్తు');
insert into year_names values(22,'సర్వధారి');
insert into year_names values(23,'విరోధి');
insert into year_names values(24,'వికృతి');
insert into year_names values(25,'ఖర');
insert into year_names values(26,'నందన');
insert into year_names values(27,'విజయ');
insert into year_names values(28,'జయ');
insert into year_names values(29,'మన్మధ');
insert into year_names values(30,'దుర్ముఖి');
insert into year_names values(31,'హేవళంబి');
insert into year_names values(32,'విళంబి');
insert into year_names values(33,'వికారి');
insert into year_names values(34,'శార్వరి');
insert into year_names values(35,'ప్లవ');
insert into year_names values(36,'శుభకృతు');
insert into year_names values(37,'శోభకృతు');
insert into year_names values(38,'క్రోధి');
insert into year_names values(39,'విశ్వావసు');
insert into year_names values(40,'పరాభవ');
insert into year_names values(41,'ప్లవంగ');
insert into year_names values(42,'కీలక');
insert into year_names values(43,'సౌమ్య');
insert into year_names values(44,'సాధారణ');
insert into year_names values(45,'విరోధికృతు');
insert into year_names values(46,'పరిధావి');
insert into year_names values(47,'ప్రమాదీచ');
insert into year_names values(48,'ఆనంద');
insert into year_names values(49,'రాక్షస');
insert into year_names values(50,'నల');
insert into year_names values(51,'పింగళ');
insert into year_names values(52,'కాళయుక్తి');
insert into year_names values(53,'సిద్ధార్ది');
insert into year_names values(54,'రౌద్రి');
insert into year_names values(55,'దుర్మతి');
insert into year_names values(56,'దుందుభి');
insert into year_names values(57,'రుధిరోద్గారి');
insert into year_names values(58,'రక్తాక్షి');
insert into year_names values(59,'క్రోధన');
insert into year_names values(60,'అక్షయ');

create table ayana_names(id int, name varchar);

insert into ayana_names values(1,'ఉత్తర');
insert into ayana_names values(2,'దక్షిణ');

create table ritu_names(id int, name varchar);

insert into ritu_names values(1,'వసంత');
insert into ritu_names values(2,'గ్రీష్మ');
insert into ritu_names values(3,'వర్ష');
insert into ritu_names values(4,'శరద్');
insert into ritu_names values(5,'హేమంత');
insert into ritu_names values(6,'శిశిర');

create table masa_names(id int, name varchar);

insert into masa_names values(1, 'చైత్ర');
insert into masa_names values(2, 'వైశాఖ');
insert into masa_names values(3, 'జ్యేష్ఠ');
insert into masa_names values(4, 'ఆషాఢ');
insert into masa_names values(5, 'శ్రావణ');
insert into masa_names values(6, 'భాద్రపద');
insert into masa_names values(7, 'ఆశ్వయుజ');
insert into masa_names values(8, 'కార్తీక');
insert into masa_names values(9, 'మార్గశిర');
insert into masa_names values(10, 'పుష్య');
insert into masa_names values(11, 'మాఘ');
insert into masa_names values(12, 'ఫాల్గుణ');

create table nakshatra_names(id int, name varchar);

insert into nakshatra_names values(1, 'అశ్విని'   );
insert into nakshatra_names values(2, 'భరణి' );
insert into nakshatra_names values(3, 'కృత్తిక' );
insert into nakshatra_names values(4, 'రోహిణి' );
insert into nakshatra_names values(5, 'మృగశిర' );
insert into nakshatra_names values(6, 'ఆరుద్ర' );
insert into nakshatra_names values(7, 'పునర్వసు' );
insert into nakshatra_names values(8, 'పుష్యమి' );
insert into nakshatra_names values(9, 'ఆశ్లేష' );
insert into nakshatra_names values(10, 'మఖ' );
insert into nakshatra_names values(11, 'పుబ్బ' );
insert into nakshatra_names values(12, 'ఉత్తర' );
insert into nakshatra_names values(13, 'హస్త' );
insert into nakshatra_names values(14, 'చిత్త' );
insert into nakshatra_names values(15, 'స్వాతి' );
insert into nakshatra_names values(16, 'విశాఖ' );
insert into nakshatra_names values(17, 'అనూరాధ' );
insert into nakshatra_names values(18, 'జ్యేష్ఠ' );
insert into nakshatra_names values(19, 'మూల' );
insert into nakshatra_names values(20, 'పూర్వాషాఢ' );
insert into nakshatra_names values(21, 'ఉత్తరాషాఢ' );
insert into nakshatra_names values(22, 'శ్రవణం' );
insert into nakshatra_names values(23, 'ధనిష్ట' );
insert into nakshatra_names values(24, 'శతభిష' );
insert into nakshatra_names values(25, 'పూర్వాభాద్ర' );
insert into nakshatra_names values(26, 'ఉత్తరాభాద్ర' );
insert into nakshatra_names values(27, 'రేవతి' );

create table thithi_names(id int, paksha varchar, name varchar);

insert into thithi_names values( 1,  'శుక్ల', 'పాడ్యమి' );
insert into thithi_names values( 2,  'శుక్ల', 'విదియ' );
insert into thithi_names values( 3,  'శుక్ల', 'తదియ' );
insert into thithi_names values( 4,  'శుక్ల', 'చవితి' );
insert into thithi_names values( 5,  'శుక్ల', 'పంచమి' );
insert into thithi_names values( 6,  'శుక్ల', 'షష్ఠి' );
insert into thithi_names values( 7,  'శుక్ల', 'సప్తమి' );
insert into thithi_names values( 8,  'శుక్ల', 'అష్టమి' );
insert into thithi_names values( 9,  'శుక్ల', 'నవమి' );
insert into thithi_names values( 10, 'శుక్ల', 'దశమి' );
insert into thithi_names values( 11, 'శుక్ల', 'ఏకాదశి' );
insert into thithi_names values( 12, 'శుక్ల', 'ద్వాదశి' );
insert into thithi_names values( 13, 'శుక్ల', 'త్రయోదశి' );
insert into thithi_names values( 14, 'శుక్ల', 'చతుర్ధశి' );
insert into thithi_names values( 15, 'శుక్ల', 'పూర్ణిమ' );
insert into thithi_names values( 16, 'కృష్ణ', 'పాడ్యమి' );
insert into thithi_names values( 17, 'కృష్ణ', 'విదియ' );
insert into thithi_names values( 18, 'కృష్ణ', 'తదియ' );
insert into thithi_names values( 19, 'కృష్ణ', 'చవితి' );
insert into thithi_names values( 20, 'కృష్ణ', 'పంచమి' );
insert into thithi_names values( 21, 'కృష్ణ', 'షష్ఠి' );
insert into thithi_names values( 22, 'కృష్ణ', 'సప్తమి' );
insert into thithi_names values( 23, 'కృష్ణ', 'అష్టమి' );
insert into thithi_names values( 24, 'కృష్ణ', 'నవమి' );
insert into thithi_names values( 25, 'కృష్ణ', 'దశమి' );
insert into thithi_names values( 26, 'కృష్ణ', 'ఏకాదశి' );
insert into thithi_names values( 27, 'కృష్ణ', 'ద్వాదశి' );
insert into thithi_names values( 28, 'కృష్ణ', 'త్రయోదశి' );
insert into thithi_names values( 29, 'కృష్ణ', 'చతుర్ధశి' );
insert into thithi_names values( 30, 'కృష్ణ', 'అమావాస్య' );